# Generated by Django 4.1.5 on 2023-01-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_add_post_content_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='network.add_post_content'),
        ),
    ]
